
# Pull request against these branches will trigger this build
pr:
- master
- staging
- maidap-sentence-similarity

#Any commit to this branch will trigger the build.
trigger:
- staging
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

- bash: |
    echo "##vso[task.prependpath]/usr/share/miniconda/bin"
  displayName: Add Conda to PATH

- bash: |
    conda remove -q -n nlp --all -y
    conda env create -f environment.yml
    conda env list  
    source activate nlp
  displayName: 'Creating Conda Environment with dependencies'

- bash: |
    source activate nlp
    python -m ipykernel install --user --name nlp --display-name "nlp"
    # Commenting out pytest since it contains bunch of tests from other project which are not applicable.
    # But keeping the line here to show how to run it once tests relevant to this project are added
    # pytest --junitxml=junit/test-unitttest.xml #not running any tests for now
  displayName: 'Run Unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-unitttest.xml'
    testRunTitle: 'Test results for PyTest'